-- return {
--   cmd = { 'intelephense', '--stdio' },
--   filetypes = { 'php' },
--   root_markers = { 'composer.json', '.git' },
--   init_options = {
--     licencekey = nil,
--   },
--   capabilities = vim.tbl_deep_extend('force', {}, vim.lsp.protocol.make_client_capabilities()),
-- }
--
return {
  cmd = { 'intelephense', '--stdio' },
  filetypes = { 'php' },
  root_markers = { 'composer.json', '.git', 'wp-config.php' },
  init_options = {
    licencekey = nil,
    stubs = {
      'apache',
      'bcmath',
      'bz2',
      'calendar',
      'com_dotnet',
      'core',
      'ctype',
      'curl',
      'date',
      'dba',
      'dom',
      'enchant',
      'exif',
      'ffi',
      'fileinfo',
      'filter',
      'fpm',
      'ftp',
      'gd',
      'gettext',
      'gmp',
      'hash',
      'iconv',
      'imap',
      'intl',
      'json',
      'ldap',
      'libxml',
      'mbstring',
      'meta',
      'mysqli',
      'mysqlnd',
      'oci8',
      'odbc',
      'openssl',
      'pcntl',
      'pcre',
      'pdo',
      'pgsql',
      'phar',
      'posix',
      'pspell',
      'readline',
      'reflection',
      'session',
      'shmop',
      'simplexml',
      'snmp',
      'soap',
      'sockets',
      'sodium',
      'spl',
      'sqlite3',
      'standard',
      'superglobals',
      'sysvmsg',
      'sysvsem',
      'sysvshm',
      'tidy',
      'tokenizer',
      'xml',
      'xmlreader',
      'xmlrpc',
      'xmlwriter',
      'xsl',
      'zip',
      'zlib',
      'wordpress', -- Add WordPress to the stubs list
    },
  },
  settings = {
    intelephense = {
      environment = {
        includePaths = {
          '/home/bekos/.config/composer/vendor/wp-coding-standards/wpcs/WordPress',
        },
      },
      files = {
        maxSize = 5000000,
      },
    },
  },
  capabilities = vim.tbl_deep_extend('force', {}, vim.lsp.protocol.make_client_capabilities()),
}
