# terminal colors
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -ga terminal-overrides ",alacritty:Tc"

# reload tmux
unbind r 
bind r source-file ~/.tmux.conf

# leader
set -g prefix C-s

# changig mode-keys from emacs to vim
set -g mode-keys vi

#add mouse support
set -g mouse on

# change window and pane indexing
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# vim like yanking
bind-key -T copy-mode-vi v send-keys -X begin-selection 
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle 
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# resize pane
bind-key -r h resize-pane -L 5
bind-key -r j resize-pane -D 5
bind-key -r k resize-pane -U 5
bind-key -r l resize-pane -R 5

# create new sections
unbind '%'
unbind '"'
bind '-' split-window  -v -c "#{pane_current_path}"
bind "\\" split-window -h -c  "#{pane_current_path}"


#move status bar to top
set-option -g status-position top


# for neovim session restoration

set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'  # Optional: save pane contents
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
# set -g @continuum-boot 'on'

# List of plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/block/blue'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'

